### ISSUE TITLE
Hide Highlight when opened. [SUGGESTION]

### ISSUE THREAD

**Issue by Paradox-Edge** [Faustvii/R2Mods#1]
I don't know why you haven't added a way to have it so the highlight goes away for opened things but not so that they're removed. I like seeing opened chests and barrels and stuff but the highlight will not go away on its own when I have opened them. I have to have the delete option on which is not what I want. Anything you can take a look at?

**Comment by Faustvii** [comment]
Good suggestion, I'll take a look at it.
