### ISSUE TITLE
Chest highlighting breaks with Spinel Tonic

### ISSUE THREAD

**Issue by Tyrusss** [Faustvii/R2Mods#11]
Interactible outlines seem to break when using Spinel Tonic due to the fov change

https://user-images.githubusercontent.com/42982810/170130134-79e14f84-2cf5-4ec3-bd72-d22c47dda6b9.mp4

**Comment by Faustvii** [comment]
I've tried very hard to replicate it but so far I haven't been able to and since I'm pretty much just using the base game highlighting I'm not sure if it's my mod or just base game issue.

**Comment by NotGumballer91** [comment]
Mine was broken as well. Here's the modlist if you need any clues. One of those maybe conflicting with it
![image](https://github.com/user-attachments/assets/0da94dd2-bba6-4940-a367-19f090812731)

**Comment by Faustvii** [comment]
So I've tried without mods and just pinging something to highlight it and the same issue is there with Spinal tonic active, so it seems to be a base game issue. So I guess it's sadly a wont/can't fix from my side.
