### ISSUE TITLE
Highlight Chest color not chaning.

### ISSUE THREAD

**Issue by NyMostWantd7** [Faustvii/R2Mods#12]
I am trying to change highlight color for chests from yellow to red/pink but it just remains with a yellow highlight. I tried restarting and the run as well as the game but to no avail. Maybe I am missing something?

**Comment by Faustvii** [comment]
Seems to work for me when testing with Pink for instance. How does your config file look? This is my color section with `Pink` color

```
## Yellow, Red, Pink
# Setting type: ConfigHighlightColor
# Default value: Yellow
# Acceptable values: Yellow, Red, Pink
Color = Pink
```

**Comment by NyMostWantd7** [comment]
This is what is looks like, assuming I am looking at the right thing.
![image_2023-01-29_151121538](https://user-images.githubusercontent.com/123828464/215353231-8a209b12-b6e4-49dc-9960-8df77f91a8c8.png)

**Comment by Faustvii** [comment]
Try writing Red or Pink instead of the value 2

**Comment by NyMostWantd7** [comment]
Copy I will try that, and let you know.

**Comment by NyMostWantd7** [comment]
Typing out the color worked, and I was even able to change colors in game, thank you for your help!

**Comment by Faustvii** [comment]
You're welcome glad it worked as expected
