### ISSUE TITLE
[QoLChests] Drone highlighting doesn't apply to StarStorm2's drones

### ISSUE THREAD

**Issue by LordVGames** [Faustvii/R2Mods#16]
Both the shock drone and duplicator drone don't have highlighting around them when drone highlighting is enabled in the config. No clue if this is an issue on SS2's end or on this mod's end.

**Comment by Faustvii** [comment]
It's most likely my mod not doing anything with the new drones, since I'm only highlighting vanilla drones. I haven't played in a while, and I don't know when I'll get around to fixing it. Is StarStorm2's drones mod on github?

**Comment by LordVGames** [comment]
Yeah, StarStorm2's on github.
https://github.com/TeamMoonstorm/Starstorm2
