### ISSUE TITLE
Gunner Drones are not highlighted. [BUG]

### ISSUE THREAD

**Issue by Paradox-Edge** [Faustvii/R2Mods#2]
Or at least they aren't always highlighted. If I manually ping them they glow just fine but yea they don't glow on their own. I don't know if any other interact-able thing doesn't glow yet I have not paid too much attention.

**Comment by Faustvii** [comment]
I would validate that the option is enabled, but highlight on turrets seems to be odd, from some angles it looks like it isn't highlighted or certain distance. Sadly nothing I can do about it.
