### ISSUE TITLE
"Hide" chests part of code ruins Artifact of Delusion.

### ISSUE THREAD

**Issue by WolfoIsBestWolf** [Faustvii/R2Mods#21]
The chests hiding should automatically be disabled if this Artifact is enabled.

Alternatively if the mod was changed to just hide the Model instead of destroying the chest entirely, the chests could reappear in a hook for "RoR2.DelusionChestController.ResetChestForDelusion".

**Comment by Faustvii** [comment]
I gave it a quick look and it seems that hook doesn't exist in my local game files, not sure if it is because I do not have the new expansion or not.

**Comment by Faustvii** [comment]
https://github.com/Faustvii/R2Mods/releases/tag/seekersstorm 
You can try this version out and see if it works at all, I haven't tested it with the Artifact, let me know how it goes.

**Comment by WolfoIsBestWolf** [comment]
First part of the report seems just fine, second part not so much.

The chests stick around, and turn invisible correctly. So Delusion works now. But their visuals do not ReAppear after being reset.

Idk what you do to "make them disappear" but like couldn't you just turn the gameObject of the model off and on off again.
![image](https://github.com/user-attachments/assets/50b9dfcf-c148-4256-821f-962e3225aede)

**Comment by Faustvii** [comment]
Thanks for testing it. I am indeed just turning the renderer off and it was supposed to turn them on again when the hook runs, could you send me the log file from the run where you test it ? Then I should be able to see if it is having trouble finding the render when the hook runs.

**Comment by WolfoIsBestWolf** [comment]
![image](https://github.com/user-attachments/assets/a72c22c5-7670-445e-bb57-507782c1d2bf)

Well looking at the code in DNSpy I think you just put false instead of true.

**Comment by WolfoIsBestWolf** [comment]
It does say this, which I guess also means it can't find the component?.  I don't remember if inactive components can be gotten via this method
[Info   : QoLChests] Delusion Chest Reset
[Info   : QoLChests] Delusion Chest Renderers: 0

**Comment by WolfoIsBestWolf** [comment]
Ah you're trying to get the Renderers of the Chest like object not the Chest Model.

You have to get the model via ModelLocator

**Comment by Faustvii** [comment]
Haha yeah I was pretty distracted when I did the release, guess I forgot to change the boolean to true. Alright I will probably take a look sometime after work, just kinda shit to not be able to test it myself, wasn't sure what the gameobject the hook would be getting was.

**Comment by Faustvii** [comment]
Alright, finally got around to it. I uploaded a new version which hopefully should do the trick, can you let me know if it works for you. https://github.com/Faustvii/R2Mods/releases/tag/seekersstorm and if it does I guess I will have to look into how to update on Thunderstore again, it's been a while...

**Comment by WolfoIsBestWolf** [comment]
[Warning:   BepInEx] Skipping type [Faust.QoLChests.QoLChests] because its version is invalid.

Don't put letters in version number, I think?. Don't think 4 piece version numbers are even supported.

Can't seem to edit it myself at all to bypass it

**Comment by Faustvii** [comment]
Well, that was dumb that I didn't test it after changing the version. I uploaded a new version on the release.

**Comment by WolfoIsBestWolf** [comment]
Yeah works perfectly now. Btw idk if you thought Delusion was DLC2, but that was just kinda randomly added to the base game.
