### ISSUE TITLE
Highlight color defaults to red after the update.

### ISSUE THREAD

**Issue by anartoast** [Faustvii/R2Mods#24]
Even when changing to another color ingame, it's still red. I opened the config and it was selected pink, changed to yellow and it was still red. 
Edit: Apparently it resets when changing stages.

**Comment by anartoast** [comment]
![image](https://github.com/user-attachments/assets/22f476a6-adac-4c99-affe-7bae5e051bfb)
...Now it's green? I'm starting to think this may be an incompat issue

**Comment by anartoast** [comment]
It can be, i'll see what is happening.

**Comment by anartoast** [comment]
I don't know if this is an issue with r2api colors but that would be a long shot.
Here's my modpack code just in case it's a super niche thing that is my fuckup or something:
0192d03c-ff36-ecb2-cef1-ed33e0bb73e0

In a fair note i'll understand if this get no priority since it's such a whateaver issue. The other aspects of the mod work.
Using this side note to say the mod is fire too, lmao.

**Comment by Faustvii** [comment]
I did a quick test with your modpack and something is changing the color. (The chest should be pink but it is not).
![image](https://github.com/user-attachments/assets/0189741e-fb8a-4480-b4c2-2a2a6b7bad61)
Either way I have confirmed that the new version of the mod that isn't released yet will not be affected by this and seems to work as intended. All it needs is some proper testing.
If you wish to test the new version for bugs, then you can find it here. (Just replace the file in the existing mod folder with the one from the release)
https://github.com/Faustvii/R2Mods/releases/tag/1.2.0

**Comment by anartoast** [comment]
![image](https://github.com/user-attachments/assets/fb900e6d-0c7c-40a0-9c79-b4dd4442f9f1)
Works just fine! Thank you.
