### ISSUE TITLE
Category chests are not properly hidden/faded

### ISSUE THREAD

**Issue by Faustvii** [Faustvii/R2Mods#27]
1. The "Symbol" is left visible
2. Large category chests are not hidden/faded at all

**Comment by WolfoIsBestWolf** [comment]
Adding to this. Shipping Terminals leave behind their impact effect. (Mesh & Particles & Light)

Idk how you get MultiShops main model but it's not working for this one.

Turning the game object off would turn off the effect tho.
![image](https://github.com/user-attachments/assets/0ac0ef0c-a8a5-45f5-8f7e-8904547795cb)

**Comment by WolfoIsBestWolf** [comment]
Another issue : Adaptive Chest collision doesn't get turned off.  Disabling the gameobject of that model would also get rid of it's colossion.

Alternatively to that easier one I guess you could do both methods destroy and hide just only Hide the ones that are devotion compatible. Or just turn off the Collider.

**Comment by Faustvii** [comment]
Thanks for doing all this testing and reporting it. Currently is a https://github.com/Faustvii/R2Mods/releases/tag/1.2.0 pre-release version here that should fix the collision/effect issues, if you want to test it, expect some bugs though, been doing some significant changes to support different colors per category as well in this version.

**Comment by WolfoIsBestWolf** [comment]
The 3 issues described seem fixed. 
However you need to turn the collider back on to be able to interact with chests for Delusion.  
With this indev version you can't use the chest after it's reset.
