### ISSUE TITLE
Suggestion: QoLChests Config setting to change highlight outline color

### ISSUE THREAD

**Issue by VarnaScelestus** [Faustvii/R2Mods#3]
Title.

**Comment by Faustvii** [comment]
I can try see what options there's possible here, but I'm just using the default highlight from the base game, so from what I remember it's pretty limited what I can change, but I'll take a look and see if there's some options.

**Comment by VarnaScelestus** [comment]
If it helps, there was similar functionality in a deprecated mod at https://thunderstore.io/package/Dragonyck/ChestHighlight/
