### ISSUE TITLE
Suggestion: Instead of completely making empty chests INVISIBLE, add an option to FADE empty chests

### ISSUE THREAD

**Issue by myd3boro** [Faustvii/R2Mods#5]
I really like your mod, but making empty chests invisible reduces the satisfaction of seeing my opened chests. 

Also, it makes it harder to see where I have been in the map. Empty chests are a good indication that I have already explored that part of the map. 

FADING empty chests strikes a good balance between utility and aesthetics. You can see it implemented in this deprecated mod:  
https://thunderstore.io/package/SSM24/FadeEmptyChests/

Thanks!

**Comment by Faustvii** [comment]
Sure, I'll look into adding this.

**Comment by myd3boro** [comment]
Awesome and quick response! Thanks!
