### ISSUE TITLE
QoL chests won't load

### ISSUE THREAD

**Issue by franky7702** [Faustvii/R2Mods#6]
I have the mod enabled but the game just won't load this mod.
Other mods work fine to me.
I've tried all the solutions [here](https://github.com/ebkr/r2modmanPlus/wiki/Why-aren't-my-mods-working%3F) and reinstalled all the mods but still don't work.

**Comment by Faustvii** [comment]
I have a theory to why, can you try and install https://thunderstore.io/package/XoXFaby/BetterUnityPlugin/ and see if it loads?

**Comment by Faustvii** [comment]
Try this version https://thunderstore.io/package/Faustvii/QoLChests/1.1.5/ it should work for you.

**Comment by franky7702** [comment]
Yeah, 1.1.5 worked for me, thanks.
