### ISSUE TITLE
the mod doesn't work

### ISSUE THREAD

**Issue by 1498886457** [Faustvii/R2Mods#7]
because of update, the mod doesn't work, hope to update the mod please.

**Comment by 1498886457** [comment]
yeah，QolChest



---Original---
From: ***@***.***&gt;
Date: Wed, Mar 16, 2022 18:37 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Faustvii/R2Mods] the mod doesn't work (Issue #7)




 
Which mod? QoLChest?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Faustvii** [comment]
Installed latest version from thunderstore? Can you provide logs from BepInEx? It works for me and my friends and seems to work for other people. So I need a bit more information on what isn't working

**Comment by 1498886457** [comment]
When I opened the game with enable QolChest only, I looked window from BepInEx which the loaded mods just contain RoR2BepInExPack 1.0.1


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Faustvii/R2Mods"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月17日(星期四) 凌晨0:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Faustvii/R2Mods] the mod doesn't work (Issue #7)





 
Installed latest version from thunderstore? Can you provide logs from BepInEx? It works for me and my friends and seems to work for other people. So I need a bit more information on what isn't working
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1498886457** [comment]
the logs from BepInEx：
[Message:   BepInEx] BepInEx 5.4.19.0 - Risk of Rain 2 (2022/3/8 18:29:55)
[Info   :   BepInEx] Running under Unity v2019.4.26.14694700
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.19.0]
[Info   :   BepInEx] 3 patcher plugins loaded
[Message:BepInEx.GUI.Patcher] Finding and launching GUI
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :   BepInEx] Patching [RoR2] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugins to load
[Info   :   BepInEx] Loading [RoR2BepInExPack 1.0.1]
[Message:   BepInEx] Chainloader startup complete
[Warning: Unity Log] Network message MsgType.Highest + 22 is unregistered.
[Info   : Unity Log] buildId = 1.2.2.0
[Info   : Unity Log] WwiseUnity: Wwise(R) SDK Version 2019.2.12 Build 7544.
[Info   : Unity Log] WwiseUnity: Setting Plugin DLL path to: C:/SteamLibrary/steamapps/common/Risk of Rain 2/Risk of Rain 2_Data\Plugins\x86_64
[Info   : Unity Log] WwiseUnity: Sound engine initialized successfully.
[Info   : Unity Log] Active scene changed from  to loadingbasic
[Info   : Unity Log] Loaded scene loadingbasic loadSceneMode=2
[Info   : Unity Log] application data path isC:/SteamLibrary/steamapps/common/Risk of Rain 2/Risk of Rain 2_Data
[Info   :   Console] Facepunch.Steamworks Unity: WindowsPlayer
[Info   :   Console] Facepunch.Steamworks Os: Windows
[Info   :   Console] Facepunch.Steamworks Arch: x64
[Info   : Unity Log] PlatformSystems:InitNetworkManagerSystem
[Info   : Unity Log] Launch Parameters: 
  arg[0]="C:\SteamLibrary\steamapps\common\Risk of Rain 2\Risk of Rain 2.exe"
  arg[1]="--doorstop-enable"
  arg[2]="true"
  arg[3]="--doorstop-target"
  arg[4]="C:\Users\14988\AppData\Roaming\r2modmanPlus-local\RiskOfRain2\profiles\Default\BepInEx\core\BepInEx.Preloader.dll"

[Info   : Unity Log] "usesocialiconflag" is not a recognized ConCommand or ConVar.
[Info   : Unity Log] Loaded archived convars.
[Info   : Unity Log] Could not load config /Config/autoexec.cfg: Could not find file "C:\SteamLibrary\steamapps\common\Risk of Rain 2\Risk of Rain 2_Data\Config\autoexec.cfg"
[Info   : Unity Log] LoadContentPacks() start
[Warning: Unity Log] Failed to assign Buffs.Deafened: Asset "bdDeafened" not found.
[Warning: Unity Log] Failed to assign Items.SummonedEcho: Asset "SummonedEcho" not found.
[Warning: Unity Log] Failed to assign Equipment.AffixEcho: Asset "EliteEchoEquipment" not found.
[Warning: Unity Log] Failed to assign Buffs.AffixEcho: Asset "bdEliteEcho" not found.
[Warning: Unity Log] Failed to assign Elites.Echo: Asset "edEcho" not found.
[Info   : Unity Log] LoadContentPacks() end
[Warning: Unity Log] Could not find scene with name "loadingbasic".
[Warning: Unity Log] Could not find scene with name "intro".
[Info   : Unity Log] Command "set_scene" failed: "intro" is not a valid scene.
[Info   : Unity Log] Game content load completed in 26541ms.
[Info   : Unity Log] Setting current language to "zh-CN"
[Info   : Unity Log] [RoR2.Stats.StatSheet] init stat sheet
[Error  : Unity Log] [RoR2.Items.BaseItemBodyBehavior] RoR2.Items.SummonedEchoBodyBehavior.GetItemDef returned null.
[Info   : Unity Log] Attempting to load user profile /UserProfiles/a093bb9a-8586-4859-a803-acbe4bad75da.xml
[Info   : Unity Log] stream.Length=245109
[Info   : Unity Log] Attempting to load user profile /UserProfiles/d18773f9-0aec-4c96-b9f2-d4cbd8314175.xml
[Info   : Unity Log] stream.Length=192775
[Info   : Unity Log] Attempting to load user profile /UserProfiles/虚空幸存者版本全解锁存档 - 副本.xml
[Info   : Unity Log] stream.Length=249537
[Info   : Unity Log] Unloaded scene loadingbasic
[Info   : Unity Log] Active scene changed from  to splash
[Info   : Unity Log] Loaded scene splash loadSceneMode=Single
[Info   : Unity Log] Setting offline scene to intro
[Info   : Unity Log] Unloaded scene splash
[Info   : Unity Log] Active scene changed from  to intro
[Info   : Unity Log] Loaded scene intro loadSceneMode=Single
[Info   : Unity Log] Setting offline scene to title
[Info   : Unity Log] Unloaded scene intro
[Info   : Unity Log] Active scene changed from  to title
[Info   : Unity Log] Loaded scene title loadSceneMode=Single
[Info   : Unity Log] BaseMainMenuScreen: OnEnter()
[Info   : Unity Log] in save archive convars
[Info   : Unity Log] Saved file "a093bb9a-8586-4859-a803-acbe4bad75da.xml" (245109 bytes)
[Info   : Unity Log] Shutting down Steamworks...
[Info   : Unity Log] Shut down Steamworks.

**Comment by Faustvii** [comment]
This sounds like an issue fixed previously, QoLChests requires the BetterUnityPlugin.dll to be in the same folder as the QoLChests.dll - see image below. The BetterUnityPlugin.dll is included by default from QoLChests version 1.1.5 and above and if you use a ModManager it should've installed both files automatically, but of course for a manual installation you need to copy both yourself.

Your mod directory for QoLChests should look like this ![image](https://user-images.githubusercontent.com/4357216/158757041-2627954c-5e09-4c62-9460-679b15efcd2d.png)

It looks like you're using R2Modman as your Mod manager which should install it correctly, but I would try and verify the folder contents (Faustvii-QoLChests), sometimes if you disable and enable a mod it can mess up and add .old to the end of the files which means they won't be loaded. It looks like your mod folder should be at `C:\Users\14988\AppData\Roaming\r2modmanPlus-local\RiskOfRain2\profiles\Default\BepInEx\plugins\Faustvii-QoLChests`

**Comment by 1498886457** [comment]
ok, I'll try it. Thanks.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月17日(星期四) 下午3:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Faustvii/R2Mods] the mod doesn't work (Issue #7)





 
This sounds like an issue fixed previously, QoLChests requires the BetterUnityPlugin.dll to be in the same folder as the QoLChests.dll - see image below. The BetterUnityPlugin.dll is included by default from QoLChests version 1.1.5 and above and if you use a ModManager it should've installed both files automatically, but of course for a manual installation you need to copy both yourself.
 
Your mod directory for QoLChests should look like this 
 
It looks like you're using R2Modman as your Mod manager which should install it correctly, but I would try and verify the folder contents (Faustvii-QoLChests), sometimes if you disable and enable a mod it can mess up and add .old to the end of the files which means they won't be loaded. It looks like your mod folder should be at C:\Users\14988\AppData\Roaming\r2modmanPlus-local\RiskOfRain2\profiles\Default\BepInEx\plugins\Faustvii-QoLChests
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
