### ISSUE TITLE
Shops don't fade

### ISSUE THREAD

**Issue by Negative232** [Faustvii/R2Mods#9]
Just an FYI, this mod runs perfectly in singleplayer yet whenever I try to use this mod in a multiplayer game, the shop terminals simply don't fade. I just wanna know why this is happening and or if this is a possible bug? (or is just me not being host of the lobby?)

**Comment by Negative232** [comment]
> It's most likely because you're not the host of the lobby, but I haven't tested it myself. If you're able to test it with being the host of the lobby, let me know. Don't have that much time lately, but I can try look into if I'm able to do something based on your findings.

Oh you believe so? I just tested it with me being the host of a lobby and they fade perfectly. I was just mainly worried that this was a possible bug. Thank you for reaching out and answering, though I do wonder if it's possible to have them fade in multiplayer without me being a host.

**Comment by Tomshiii** [comment]
I have been having this same issue since sots (I think..? I don't remember it happening beforehand but I might be placeboing that)

**Comment by Faustvii** [comment]
You're probably correct that you see it more as a client after SOTS, previously if the people(host) you played with also had the mod installed, they would have essentially removed the shop for you, but now the mod works differently since I changed it to not break for Artifact of delusion, so the shops/chests are no longer destroyed from the game, just hidden. 

I have been working on a new update that should fix this issue, as well some other features, there is an test build available here. https://github.com/Faustvii/R2Mods/releases/tag/1.2.0 

Everything should work, but I haven't had much time to test it, so any help with testing it would be appreciated.

**Comment by Tomshiii** [comment]
I appreciate the response/explanation!
I'd love to give it a test for you, I just won't be able to jump in until the end of the week, busy work week and all. But if that's not too late I'll try to give it a crack and report back 🫡

**Comment by Tomshiii** [comment]
okay hi, sorry life really went and got in the way there.
Finally managed to get into a game with a friend today - I can confirm it does seem like fading is working which is great!
However it seems that multishop highlighting for items has gone wonky and the items themselves don't highlight anymore (they did fix this in the patch... right..? lol).
Other than that I didn't notice anything else in my short session today, love the ability to colour different stuff a bunch of different colours!


![20241104203957_1](https://github.com/user-attachments/assets/b0be835e-cc02-4603-a537-0a12fd5ad7aa)
![20241104230412_1](https://github.com/user-attachments/assets/fcb0ab60-c9ab-455b-bc7d-74a8a8d1bcb3)

**Comment by Faustvii** [comment]
@Tomshiii Thanks a lot for test, that was a great spot with the item pickup losing their highlights. It led me to find a few other bugs as well. 
I have uploaded a new version on https://github.com/Faustvii/R2Mods/releases/tag/1.2.0 that should hopefully be working as expected now without this unintended side effect. 
If you would like to test that again at your leisure that would be awesome.

**Comment by Tomshiii** [comment]
Was a bit worried at first as the new version didn't seem to change anything until I realised BepInEx is a sneaky one and has it too. Unfortunately my friend is sick today so could only try in a singleplayer run but seems to be working as expected 🫡 
![20241108210826_1](https://github.com/user-attachments/assets/4a6c189d-9827-4b69-b232-c0b6593fb0bc)
